### ISSUE TITLE
Number of cards

### ISSUE THREAD

**Issue by faneaatiku** [1ds/equiminer#1]
It looks like people are complaining that the miner can only be used on systems with 6 GPUs. Can something be done about that ?

**Comment by faneaatiku** [comment]
Got in touch with NinjaPickle, he said that it supports 8 cards and the next version will support MAX cards supported by OS. Closing as invalid.

**Comment by NinjaPickle** [comment]
Current versions (as of 2.2.13) support up to 8 GPU's.
