### ISSUE TITLE
Help with Equiminer 2.3.3 not seeing all my gpu's

### ISSUE THREAD

**Issue by Braddb** [1ds/equiminer#4]
I have 2 rigs.
1 x 6 GPU and equiminer recognizes all GPU's
1 x 3 GPU and equiminer can only see 1 GPU. 
CCMiner and any other mining software on this machine can see all 3...
Can anyone shed any light?

**Comment by NinjaPickle** [comment]
Are any of the cards not seen AMD?  You need to specifically activate AMD support on the config page.

**Comment by Braddb** [comment]
Hi. Thanks for getting back to me. No they are all Nvidia. It recognizes 1
but not the other 2. The other 2 are seen in Windows and CCminer can use
all 3

**Comment by NinjaPickle** [comment]
I'm not sure about CCminer.  I use DSTM by default to detect cards with the following call:
zm --list-devices

Try this.  Turn on AMD support on the config page.  Restart EquiMiner, and see if it see's the cards?  When AMD support is enabled, I use Optiminer instead to detect cards.  Maybe it will have better luck seeing those GPU's?

**Comment by Braddb** [comment]
Wow... Thanks bro.. I enabled AMD support (even though they are nvidia
cards?) and it now sees all of my GPU's
Legend.... Thanks.
Bradd
