### ISSUE TITLE
Cannot connect to the pool (Equiminer 2.5.2)

### ISSUE THREAD

**Issue by BillMarks7** [1ds/equiminer#6]
![img_4422](https://user-images.githubusercontent.com/40337577/41508644-ad055aac-720d-11e8-863a-d53512c39e74.jpg)
![img_4423](https://user-images.githubusercontent.com/40337577/41508645-ad1e2f96-720d-11e8-954d-da4eedb2fcc2.jpg)

**Comment by NinjaPickle** [comment]
This should be resolved with 2.5.3, and EquiMiner no longer tries to mine to dev pool since BTCZ has forked.
